web/azureus/src/Custom/AzureusBundle/Entity/Art.php
<?php

namespace Custom\AzureusBundle\Entity;

use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Doctrine\Common\Collections\ArrayCollection;


/**
 * Art
 *
 * @ORM\Table()
 * @ORM\Entity
 */
class Art
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="string", length=255)
     */
    private $description;

    /**
     * @var string
     *
     * @ORM\Column(name="path", type="string", length=255)
     */
    private $path;
    
    /**
     * @ORM\ManyToOne(targetEntity="User", inversedBy="gallery")
     * @ORM\JoinColumn(name="owner_id", referencedColumnName="id", onDelete="CASCADE")
     */
    private $owner;
    
    /**
     * @ORM\OneToMany(targetEntity="ArtComment", mappedBy="parent")
     */
    private $comments;
    
    /**
     * @Assert\File(maxSize="6000000")
     */
    private $file;
    
    /**
     * @var \DateTime date
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(name="date", type="datetime")
     */
    private $date;
    
    
    /**
     * @ORM\ManyToMany(targetEntity="User", mappedBy="favourites")
     **/
    private $favourites;


    function __construct() {
        //$this->date = new \DateTime();
        $this->favourites = new \Doctrine\Common\Collections\ArrayCollection();
        $this->comments = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set description
     *
     * @param string $description
     * @return Art
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string 
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set path
     *
     * @param string $path
     * @return Art
     */
    public function setPath($path)
    {
        $this->path = $path;

        return $this;
    }

    /**
     * Get path
     *
     * @return string 
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Set date
     *
     * @param \DateTime $date
     * @return Art
     */
    public function setDate($date)
    {
        $this->date = $date;

        return $this;
    }

    /**
     * Get date
     *
     * @return \DateTime 
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * Set owner
     *
     * @param \Custom\AzureusBundle\Entity\User $owner
     * @return Art
     */
    public function setOwner(\Custom\AzureusBundle\Entity\User $owner = null)
    {
        $this->owner = $owner;

        return $this;
    }

    /**
     * Get owner
     *
     * @return \Custom\AzureusBundle\Entity\User 
     */
    public function getOwner()
    {
        return $this->owner;
    }


    /**
     * Add favourites
     *
     * @param \Custom\AzureusBundle\Entity\User $favourites
     * @return Art
     */
    public function addFavourite(\Custom\AzureusBundle\Entity\User $favourites)
    {
        $this->favourites[] = $favourites;

        return $this;
    }

    /**
     * Remove favourites
     *
     * @param \Custom\AzureusBundle\Entity\User $favourites
     */
    public function removeFavourite(\Custom\AzureusBundle\Entity\User $favourites)
    {
        $this->favourites->removeElement($favourites);
    }

    /**
     * Get favourites
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getFavourites()
    {
        return $this->favourites;
    }
    
    public function getAbsolutePath()
    {
        return null === $this->path
            ? null
            : $this->getUploadRootDir().'/'.$this->path;
    }
    public function getWebPath()
    {
        return null === $this->path
            ? null
            : $this->getUploadDir().'/'.$this->path;
    }
    protected function getUploadRootDir()
    {
        // the absolute directory path where uploaded
        // documents should be saved
        return __DIR__.'/../../../../web/'.$this->getUploadDir();
    }
    protected function getUploadDir()
    {
        // get rid of the __DIR__ so it doesn't screw up
        // when displaying uploaded doc/image in the view.
        return 'uploads/arts';
    }
    
    /**
     * Sets file.
     *
     * @param UploadedFile $file
     */
    public function setFile(UploadedFile $file = null)
    {
        $this->file = $file;
    }
    
    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preUpload()
    {
        if (null !== $this->getFile()) {
            // do whatever you want to generate a unique name
            $filename = sha1(uniqid(mt_rand(), true));
            $this->path = $filename.'.'.$this->getFile()->guessExtension();
        }
    }
    /**
     * Get file.
     *
     * @return UploadedFile
     */
    public function getFile()
    {
        return $this->file;
    }
    
    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload()
    {
//        // the file property can be empty if the field is not required
//        if (null === $this->getFile()) {
//            return;
//        }
////        // use the original file name here but you should
////        // sanitize it at least to avoid any security issues
////
////        // move takes the target directory and then the
////        // target filename to move to
////        $this->getFile()->move(
////            $this->getUploadRootDir(),
////            $this->getFile()->getClientOriginalName()
////        );
////
////        // set the path property to the filename where you've saved the file
////        $this->path = $this->getFile()->getClientOriginalName();
////
////        // clean up the file property as you won't need it anymore
////        $this->file = null;
//                // if there is an error when moving the file, an exception will
//        // be automatically thrown by move(). This will properly prevent
//        // the entity from being persisted to the database on error
//        $this->getFile()->move($this->getUploadRootDir(), $this->path);
//        // check if we have an old image
//        if (isset($this->temp)) {
//            // delete the old image
//            unlink($this->getUploadRootDir().'/'.$this->temp);
//            // clear the temp image path
//            $this->temp = null;
//        }
//        $this->file = null;
        
            // the file property can be empty if the field is not required
        if (null === $this->getFile()) {
            return;
        }

        // use the original file name here but you should
        // sanitize it at least to avoid any security issues

        // move takes the target directory and then the
        // target filename to move to
        $this->getFile()->move(
            $this->getUploadRootDir(),
            $this->getFile()->getClientOriginalName()
        );

        // set the path property to the filename where you've saved the file
        $this->path = $this->getFile()->getClientOriginalName();

        // clean up the file property as you won't need it anymore
        $this->file = null;
    }
    
    /**
     * @ORM\PostRemove()
     */
    public function removeUpload()
    {
        $file = $this->getAbsolutePath();
        if ($file) {
            unlink($file);
        }
    }

    /**
     * Add comments
     *
     * @param \Custom\AzureusBundle\Entity\ArtComment $comments
     * @return Art
     */
    public function addComment(\Custom\AzureusBundle\Entity\ArtComment $comments)
    {
        $this->comments[] = $comments;

        return $this;
    }

    /**
     * Remove comments
     *
     * @param \Custom\AzureusBundle\Entity\ArtComment $comments
     */
    public function removeComment(\Custom\AzureusBundle\Entity\ArtComment $comments)
    {
        $this->comments->removeElement($comments);
    }

    /**
     * Get comments
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getComments()
    {
        return $this->comments;
    }
    
    public function getClassName()
    {
        return (new \ReflectionClass($this))->getShortName();
    }
}

web/azureus/src/Custom/AzureusBundle/Entity/User.php
<?php

namespace Custom\AzureusBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Doctrine\Common\Collections\ArrayCollection;

use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * User
 *
 * @ORM\Table()
 * @ORM\Entity
 * @UniqueEntity("username")
 */
class User implements UserInterface {

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="username", type="string", length=30)
     */
    private $username;

    /**
     * @var string
     *
     * @ORM\Column(name="password", type="string", length=64)
     */
    private $password;

    /**
     * @ORM\OneToMany(targetEntity="Art", mappedBy="owner")
     */
    private $gallery;

    /**
     * @var UserInfo
     * 
     * @ORM\OneToOne(targetEntity="UserInfo", mappedBy="owner", cascade={"persist", "remove"})
     * */
    private $info;

    /**
     * @ORM\OneToMany(targetEntity="Post", mappedBy="owner")
     */
    private $journal;

    /**
     * @ORM\ManyToMany(targetEntity="Art", inversedBy="favourites")
     * @ORM\JoinTable(name="users_favourites")
     * */
    private $favourites;

    /**
     * @ORM\ManyToMany(targetEntity="Post", inversedBy="favourite_posts")
     * @ORM\JoinTable(name="users_favourite_posts")
     * */
    private $favourite_posts;

    function __construct() {
        $this->favourites = new \Doctrine\Common\Collections\ArrayCollection();
        $this->journal = new \Doctrine\Common\Collections\ArrayCollection();
        $this->gallery = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set username
     *
     * @param string $username
     * @return User
     */
    public function setUsername($username) {
        $this->username = $username;

        return $this;
    }

    /**
     * Get username
     *
     * @return string 
     */
    public function getUsername() {
        return $this->username;
    }

    /**
     * Set password
     *
     * @param string $password
     * @return User
     */
    public function setPassword($password) {
        $this->password = password_hash($password, PASSWORD_BCRYPT);

        return $this;
    }

    /**
     * Get password
     *
     * @return string 
     */
    public function getPassword() {
        return $this->password;
    }

    public function __toString() {
        return $this->username;
    }

    public function getSalt() {
        return null;
    }

    public function getRoles() {
        return array('ROLE_USER');
    }

    public function eraseCredentials() {
        
    }

    /**
     * Add gallery
     *
     * @param \Custom\AzureusBundle\Entity\Art $gallery
     * @return User
     */
    public function addGallery(\Custom\AzureusBundle\Entity\Art $gallery) {
        $this->gallery[] = $gallery;

        return $this;
    }

    /**
     * Remove gallery
     *
     * @param \Custom\AzureusBundle\Entity\Art $gallery
     */
    public function removeGallery(\Custom\AzureusBundle\Entity\Art $gallery) {
        $this->gallery->removeElement($gallery);
    }

    /**
     * Get gallery
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getGallery() {
        return $this->gallery;
    }

    /**
     * Set info
     *
     * @param \Custom\AzureusBundle\Entity\UserInfo $info
     * @return User
     */
    public function setInfo(\Custom\AzureusBundle\Entity\UserInfo $info = null) {
        $this->info = $info;

        return $this;
    }

    /**
     * Get info
     *
     * @return \Custom\AzureusBundle\Entity\UserInfo 
     */
    public function getInfo() {
        return $this->info;
    }

    /**
     * Add journal
     *
     * @param \Custom\AzureusBundle\Entity\Post $journal
     * @return User
     */
    public function addJournal(\Custom\AzureusBundle\Entity\Post $journal) {
        $this->journal[] = $journal;

        return $this;
    }

    /**
     * Remove journal
     *
     * @param \Custom\AzureusBundle\Entity\Post $journal
     */
    public function removeJournal(\Custom\AzureusBundle\Entity\Post $journal) {
        $this->journal->removeElement($journal);
    }

    /**
     * Get journal
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getJournal() {
        return $this->journal;
    }

    /**
     * Add favourites
     *
     * @param \Custom\AzureusBundle\Entity\Art $favourites
     * @return User
     */
    public function addFavourite(\Custom\AzureusBundle\Entity\Art $favourites) {
        $this->favourites[] = $favourites;

        return $this;
    }

    /**
     * Remove favourites
     *
     * @param \Custom\AzureusBundle\Entity\Art $favourites
     */
    public function removeFavourite(\Custom\AzureusBundle\Entity\Art $favourites) {
        $this->favourites->removeElement($favourites);
    }

    /**
     * Get favourites
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getFavourites() {
        return $this->favourites;
    }

    /**
     * Add favourite_posts
     *
     * @param \Custom\AzureusBundle\Entity\Art $favourite_posts
     * @return User
     */
    public function addFavouritePost(\Custom\AzureusBundle\Entity\Post $favourite_posts) {
        $this->favourite_posts[] = $favourite_posts;

        return $this;
    }

    /**
     * Remove favourite_posts
     *
     * @param \Custom\AzureusBundle\Entity\Art $favourite_posts
     */
    public function removeFavouritePost(\Custom\AzureusBundle\Entity\Post $favourite_posts) {
        $this->favourite_posts->removeElement($favourite_posts);
    }

    /**
     * Get favourites
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getFavouritePosts() {
        return $this->favourite_posts;
    }

}

web/azureus/src/Custom/AzureusBundle/Form/UserType.php
<?php
namespace Custom\AzureusBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class UserType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('username')
            ->add('password', 'password') //drugi argument robi input jako password
        ;
        
        $builder->add('info', new UserInfoType());
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Custom\AzureusBundle\Entity\User'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'custom_azureusbundle_user';
    }
}

web/azureus/src/Custom/AzureusBundle/Resources/views/User/edit.html.twig
{% extends '::base.html.twig' %}

{% block body -%}
    <h1>User edit</h1>

    {{ form(edit_form) }}

        <ul class="record_actions">
    <li>
        <a href="{{ path('admin_user') }}">
            Back to the list
        </a>
    </li>
    {% if is_granted('ROLE_ADMIN') %}
        <li>{{ form(delete_form) }}</li>
    {% endif %} 
</ul>
{% endblock %}

web/azureus/src/Custom/AzureusBundle/Resources/views/User/gallery.html.twig
{% extends '::base.html.twig' %}

{% block body -%}
     {% for art in arts %}
        <div class="art">
            <h3>{{ art.description }}</h1>
            <p>
                <span>{{ art.date|date('Y-m-d H:i:s') }}</span>
                |
                <a href="{{ path('show_profile', { 'username': art.owner }) }}">
                    {{ art.owner }}
                </a>
            </p>
            <p><a href="{{ path('art_show', {id: art.id})}}" ><img class="art" src="{{ art.WebPath | imagine_filter('my_thumb') }}" /> </a></p>
        </div>
    {% endfor %}
{% endblock %}

web/azureus/src/Custom/AzureusBundle/Resources/views/User/index.html.twig
{% extends '::base.html.twig' %}

{% block body -%}
    <h1>User list</h1>

    <table class="records_list">
        <thead>
            <tr>
                <th>Id</th>
                <th>Username</th>
                <th>Password</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for entity in entities %}
            <tr>
                <td><a href="{{ path('admin_user_show', { 'id': entity.id }) }}">{{ entity.id }}</a></td>
                <td>{{ entity.username }}</td>
                <td>{{ entity.password|slice(0,20) }}</td>
                <td>
                <ul>
                    <li>
                        <a href="{{ path('admin_user_show', { 'id': entity.id }) }}">show</a>
                    </li>
                    <li>
                        <a href="{{ path('admin_user_edit', { 'id': entity.id }) }}">edit</a>
                    </li>
                </ul>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

        <ul>
        <li>
            <a href="{{ path('admin_user_new') }}">
                Create a new entry
            </a>
        </li>
    </ul>
    {% endblock %}

web/azureus/src/Custom/AzureusBundle/Resources/views/User/journal.html.twig
{% extends '::base.html.twig' %}

{% block body -%}
     {% for post in posts %}
        <div>
            <h3>{{ post.title }}</h1>
            <p>
                <span>{{ post.date|date('Y-m-d H:i:s') }}</span>
                |
                <a href="{{ path('show_profile', { 'username': post.owner }) }}">
                    {{ post.owner }}
                </a>
            </p>
            <p>
                {{ post.content }}
            </p>
        </div>
    {% endfor %}
{% endblock %}

web/azureus/src/Custom/AzureusBundle/Resources/views/User/new.html.twig
{% extends '::base.html.twig' %}

{% block body -%}
    <h1>User creation</h1>

    {{ form(form) }}

        <ul class="record_actions">
    <li>
        <a href="{{ path('admin_user') }}">
            Back to the list
        </a>
    </li>
</ul>
{% endblock %}

web/azureus/src/Custom/AzureusBundle/Resources/views/User/profile.html.twig
{% extends '::base.html.twig' %}

{% block body -%}
    <h1>User</h1>

    <table class="record_properties">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ user.id }}</td>
            </tr>
            <tr>
                <th>Username</th>
                <td>{{ user.username }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ user.info.name }}</td>
            </tr>
            <tr>
                <th>Surname</th>
                <td>{{ user.info.surname }}</td>
            </tr>
            <tr>
                <th>Bio</th>
                <td>{{ user.info.bio }}</td>
            </tr>
            <tr>
                <th>Country</th>
                <td>{{ user.info.country }}</td>
            </tr>
        </tbody>
    </table>

    <div>
        <h2><a href="{{ path('show_gallery', { 'username': user.username }) }}"> Arts </a></h2>
        <table>
        {% for art in arts %}
            <tr>
                <td><a href="{{ path('art_show', { 'id': art.id }) }}">{{ art.id }}</a></td>
                <td>{{ art.description }}</td>
                <td>{{ art.path|slice(0,20) }}</td>
                <td>   
                    {% if art.owner is not defined %}
                        Admin
                    {% else %}
                        {{ art.owner.username }}
                    {% endif %}               
                </td>
                <td>
                     <img src="{{ art.WebPath | imagine_filter('my_thumb') }}" />
                </td>
            </tr>
        {% endfor %}
        </table>
    </div>
        
    <div>
        <h2> <a href="{{ path('show_journal', { 'username': user.username }) }}"> Posts </a> </h2>
        {% for post in posts %}
            <div>
                <h4>{{ post.title }}</h4>
                <h5>{{ post.date|date('Y-m-d H:i:s') }}</h5>
                <p>{{ post.content }}</p>
            </div>
        {% endfor %}
    </div>
        
        <h3>Last comments</h3>
                {% for comment in comments %}
                {% if comment.parent is not null %}
                    object: {{ comment.parent.id }}
                    type: {{ comment.parent.className }}
                    date: {{ comment.date|date('Y-m-d H:i:s')  }}
                    
                        {% if comment.parent.className == 'Post' %} 
                            <a href="{{ path('post_show', { 'id': comment.parent.id }) }}"> Post </a>
                        {% elseif comment.parent.className == 'Art' %}
                            <a href="{{ path('art_show', { 'id': comment.parent.id }) }}"> Art </a>
                        {% endif %}
                    <p>
                        {{ comment.content }}
                    </p>
                {% endif %}
            {% endfor %}

        <h3>Favourites</h3>
        {% for art in user.favourites %}
             <a href="{{ path('art_show', { 'id': art.id }) }}"> {{ art.description }} </a>
        {% endfor %}
{% endblock %}

web/azureus/src/Custom/AzureusBundle/Resources/views/User/show.html.twig
{% extends '::base.html.twig' %}

{% block body -%}
    <h1>User</h1>

    <table class="record_properties">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ entity.id }}</td>
            </tr>
            <tr>
                <th>Username</th>
                <td>{{ entity.username }}</td>
            </tr>
            <tr>
                <th>Password</th>
                <td>{{ entity.password|slice(0,20) }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ entity.info.name }}</td>
            </tr>
            <tr>
                <th>Surname</th>
                <td>{{ entity.info.surname }}</td>
            </tr>
            <tr>
                <th>Bio</th>
                <td>{{ entity.info.bio }}</td>
            </tr>
            <tr>
                <th>Country</th>
                <td>{{ entity.info.country }}</td>
            </tr>
        </tbody>
    </table>

        <ul class="record_actions">
    <li>
        <a href="{{ path('admin_user') }}">
            Back to the list
        </a>
    </li>
    <li>
        <a href="{{ path('admin_user_edit', { 'id': entity.id }) }}">
            Edit
        </a>
    </li>
    <li>{{ form(delete_form) }}</li>
</ul>
{% endblock %}